---

- name: Show objects
  debug:
    msg: "Name: {{ object_name }} - Type: {{ object_type }}"

# Get device under Pinning Policy
- name: Get existing objects pinned on the device
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/adc-core/working-config/root-node?$filter=deviceReference.machineId%20eq%20'{{ machine_id }}'"
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: json_response

- name: Get the RootNode ID
  set_fact:
    root_node_id: "{{ json_response | json_query(query) }}"
  vars: 
    query: "json.items[0].id"

# Get existing object already pin on the device
- name: Get the existing objects
  set_fact:
    existing_objects: "{{ json_response | json_query(query) }}"
  vars: 
    query: "json.items[0].{{ object_type }}"

#- debug:
#    var: existing_objects

- name: Set Objets metadata
  set_fact:
    objects_metadata: "{{ lookup('file', 'files/objects_metadata.json', errors='strict') }}"

- name: Get object details 
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}{{ objects_metadata['components']['ltm']['endpoints'][object_type]['uri'] }}?$filter=name%20eq%20'{{ object_name }}'"
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: json_response

- name: Get kind of the object to pin
  set_fact:
    object_kind: "{{ json_response | json_query(query) }}"
  vars: 
    query: "json.items[0].kind"

- name: Get id of the object to pin
  set_fact:
    object_id: "{{ json_response | json_query(query) }}"
  vars: 
    query: "json.items[0].id"

- name: new array of the object to pin
  set_fact:
    new_object_pin: '{ "id": "{{ object_id }}", "kind": "{{ object_kind }}", "link": "https://localhost{{ objects_metadata["components"]["ltm"]["endpoints"][object_type]["uri"] }}/{{ object_id }}", "name": "{{ object_name }}"}'

- debug:
    var: new_object_pin

- name: existing_objects + new_objects
  set_fact:
    all_objects: "{{ existing_objects + [ new_object_pin ] }}"

- name: Pinning objects to the device
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/adc-core/working-config/root-node/{{ root_node_id }}"
    method: PATCH
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      Content-Type: application/json
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    body: |
      {
        "name": "RootNode",
        "id": "{{ root_node_id }}",
        "deviceReference": {
          "id": "{{ machine_id }}",
          "kind": "shared:resolver:device-groups:restdeviceresolverdevicestate",
          "link": "https://localhost/mgmt/shared/resolver/device-groups/cm-adccore-allbigipDevices/devices/{{ machine_id }}"
        },
        "{{ object_type }}": {{ all_objects }}
      }
    body_format: json
  register: json_response
