---
- name: Setup provider and varables
  set_fact:
    provider: "{{ provider }}"

- name: Get authentication token
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/authn/login"
    method: POST
    timeout: "{{ timeout }}"
    validate_certs: "{{ provider.validate_certs }}"
    body:
      username: "{{ provider.user }}"
      password: "{{ provider.password }}"
      loginProviderName: "{{ provider.auth_provider | default('tmos') }}"
    body_format: json
  register: authtoken

- name: Set the token fact if authentication succeeded
  set_fact:
    f5_auth_token: "{{ authtoken.json.token.token }}"
  when: authtoken is success

- name: Test authentication
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/echo"
    timeout: "{{ timeout }}"
    validate_certs: "{{ provider.validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: status

- name: Get device provisioning type
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/system/provisioning"
    timeout: "{{ timeout }}"
    validate_certs: "{{ provider.validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: rprov

- name: Fail if you're running the role against a DCD device
  fail:
    msg: "This role should be run against a CM device, but you appear to be running it against a DCD device"
  when: rprov.json.systemPersonality == 'logging_node'

- name: Check if system is setup
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/system/setup"
    timeout: "{{ timeout }}"
    validate_certs: "{{ provider.validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: setupchk

- name: Stop if the system is not setup
  fail:
    msg: "The CM device has not been setup. Please onboard the DCD device first."
  when: setupchk.json.isSystemSetup is not defined or not setupchk.json.isSystemSetup|bool

- name: Show all objects to be pinned and deployed (optional)
  vars:
    module: "{{ item.0.name }}"
    object_name: "{{ item.1.name }}"
    object_type: "{{ item.1.type }}"
  debug:
    msg: "Module: {{ module }} - Name: {{ object_name }} - Type: {{ object_type }}"
  with_subelements:
    - "{{ modules }}"
    - pin
    - skip_missing: True

- name: Show all objects to be unpinned and removed (optional)
  vars:
    module: "{{ item.0.name }}"
    object_name: "{{ item.1.name }}"
    object_type: "{{ item.1.type }}"
  debug:
    msg: "Module: {{ module }} - Name: {{ object_name }} - Type: {{ object_type }}"
  with_subelements:
    - "{{ modules }}"
    - unpin
    - skip_missing: True

# Only identify Standalone and Cluster (with max 2 devices)
- name: Run task to find device in BIG-IQ
  include_tasks: "bigiq-find-device.yaml"

# Need to pin only to one device even if part of the cluster, BIG-IQ will add it automatically to the other members
# machine_id2 is not used
- name: Run task Pinning objects
  include_tasks: "bigiq-pinning.yaml"
  vars:
    module: "{{ item.0.name }}"
    object_name: "{{ item.1.name }}"
    object_type: "{{ item.1.type }}"
  with_subelements:
    - "{{ modules }}"
    - pin
    - skip_missing: True

- name: Run task Un-Pinning objects
  include_tasks: "bigiq-unpinning.yaml"
  vars:
    module: "{{ item.0.name }}"
    object_name: "{{ item.1.name }}"
    object_type: "{{ item.1.type }}"
  with_subelements:
    - "{{ modules }}"
    - unpin
    - skip_missing: True

#### for items in pin => DEPLOY
# For deployment, need to specify all members of the cluster
# machine_id2 is used for clusters here
- name: Run task deploy objects to BIG-IP
  include_tasks: "bigiq-deploy.yaml"
  when:
    - not skip_deploy | bool

#### for items in unpin => EVAL ONLY
# For deployment, need to specify all members of the cluster
# machine_id2 is used for clusters here
- name: Run task deploy objects to BIG-IP
  include_tasks: "bigiq-evaluation-only.yaml"
  when:
    - not skip_deploy | bool
    